export const PRESET_TICKET_TEMPLATES = [
  {
    name: "Multi-Category Dropdown Support Hub",
    description: "Modern Components V2 layout with select menu for Technical, Billing & General Support.",
    layoutMode: "components_v2" as const,
    accentColor: "#5865F2",
    spoiler: false,
    containerConfig: [
      {
        id: "block-sec-1",
        type: "section" as const,
        content: "# 🎫 Help & Support Center\nWelcome to our customer service desk! Please select your support inquiry from the dropdown menu below.",
        accessory: {
          type: "thumbnail" as const,
          url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150",
        },
      },
      { id: "block-sep-1", type: "separator" as const, divider: true },
      {
        id: "block-txt-guide",
        type: "text" as const,
        content: "### 📌 Before opening a ticket:\n- Please check our announcements for known outages.\n- Have your transaction or account ID ready if asking about billing.\n- Staff response times are typically under **15 minutes**.",
      },
      { id: "block-sep-2", type: "separator" as const, divider: false },
      {
        id: "block-row-select",
        type: "action_row" as const,
        rowType: "select" as const,
        selectMenu: {
          id: "sel-hub",
          type: "string_select" as const,
          placeholder: "Choose a ticket department...",
          options: [
            {
              label: "🛠️ Technical Support",
              value: "tech_support",
              description: "Hardware, software, bot or connection issues",
              actionType: "CREATE_TICKET" as const,
              ticketTypeId: "tech_support",
            },
            {
              label: "💳 Billing & Payments",
              value: "billing",
              description: "Subscriptions, invoices, refunds & purchases",
              actionType: "CREATE_TICKET" as const,
              ticketTypeId: "billing",
            },
            {
              label: "❓ General Inquiries",
              value: "general",
              description: "General server questions and member support",
              actionType: "CREATE_TICKET" as const,
              ticketTypeId: "general",
            },
          ],
        },
      },
    ],
    ticketTypesConfig: [
      {
        id: "tech_support",
        name: "Technical Support",
        label: "🛠️ Technical Support",
        emoji: "🛠️",
        description: "Hardware, software or connection issues",
        namingFormat: "tech-{username}",
        welcomeTitle: "🛠️ Technical Support Ticket",
        welcomeDescription: "Welcome {user}! Please describe the issue you are experiencing and include error logs or screenshots.",
        welcomeColor: "#5865F2",
        questions: [
          { id: "q1", label: "What device or OS are you using?", placeholder: "e.g. Windows 11, Chrome", style: "short" as const, required: true },
          { id: "q2", label: "Describe the bug/issue in detail", placeholder: "Explain what happened...", style: "paragraph" as const, required: true },
        ],
      },
      {
        id: "billing",
        name: "Billing & Inquiries",
        label: "💳 Billing & Payments",
        emoji: "💳",
        description: "Subscriptions, invoices & purchases",
        namingFormat: "billing-{username}",
        welcomeTitle: "💳 Billing Support Ticket",
        welcomeDescription: "Welcome {user}! An accounts representative will assist you shortly.",
        welcomeColor: "#F0B232",
        questions: [
          { id: "q1", label: "Transaction or Invoice ID", placeholder: "e.g. INV-109283", style: "short" as const, required: true },
        ],
      },
      {
        id: "general",
        name: "General Inquiry",
        label: "❓ General Inquiries",
        emoji: "❓",
        description: "General questions and server help",
        namingFormat: "ticket-{username}",
        welcomeTitle: "👋 General Support Ticket",
        welcomeDescription: "Welcome {user}! How can our support staff help you today?",
        welcomeColor: "#23A55A",
      },
    ],
  },
  {
    name: "Modern Interactive Buttons Support",
    description: "Clean layout with direct creation buttons for fast 1-click ticket opening.",
    layoutMode: "components_v2" as const,
    accentColor: "#23A55A",
    spoiler: false,
    containerConfig: [
      {
        id: "block-txt-header",
        type: "text" as const,
        content: "# 🚀 Need Quick Support?\nClick one of the buttons below to instantly open a private channel with our staff team.",
      },
      { id: "block-sep-1", type: "separator" as const, divider: true },
      {
        id: "block-sec-1",
        type: "section" as const,
        content: "**Standard Member Support**\nGet fast help with roles, permissions, or community questions.",
        accessory: {
          type: "button" as const,
          style: "Primary" as const,
          label: "Open Ticket",
          emoji: "📩",
          actionType: "CREATE_TICKET" as const,
          ticketTypeId: "general",
        },
      },
      {
        id: "block-sec-2",
        type: "section" as const,
        content: "**Report a Rule Violation / Bug**\nDiscreetly submit reports to server moderators and developers.",
        accessory: {
          type: "button" as const,
          style: "Danger" as const,
          label: "Submit Report",
          emoji: "🚨",
          actionType: "CREATE_TICKET" as const,
          ticketTypeId: "reports",
        },
      },
    ],
    ticketTypesConfig: [
      {
        id: "general",
        name: "General Support",
        label: "General Support",
        emoji: "📩",
        description: "Standard support",
        namingFormat: "ticket-{username}",
        welcomeTitle: "👋 Support Ticket #{number}",
        welcomeDescription: "Welcome {user}! A supporter will be with you shortly.",
        welcomeColor: "#5865F2",
      },
      {
        id: "reports",
        name: "Reports & Moderation",
        label: "Reports",
        emoji: "🚨",
        description: "Rule violations and bugs",
        namingFormat: "report-{username}",
        welcomeTitle: "🚨 Moderation Report #{number}",
        welcomeDescription: "Hello {user}. Please paste user tags or description below.",
        welcomeColor: "#F23F43",
        questions: [
          { id: "q1", label: "User or Rule violated", placeholder: "e.g. @Spammer", style: "short" as const, required: true },
          { id: "q2", label: "Evidence or details", placeholder: "Message link or description...", style: "paragraph" as const, required: true },
        ],
      },
    ],
  },
];
